#!/bin/sh

#
# Script which configures the resinOS_uEnv,txt to use an updated root index
#

set -o errexit

new_part=$(findmnt --noheadings --canonicalize --output SOURCE "/mnt/sysroot/inactive")
blockdev=$(basename "$new_part")
new_part_idx=$(cat "/sys/class/block/$blockdev/partition")
new_part_idx=$(printf '0x%x' "$new_part_idx")

printf "[INFO] Switching uboot root partition index to %s..." "$new_part_idx..."
echo "resin_root_part=$new_part_idx" > /mnt/boot/resinOS_uEnv.txt.new
sync -f /mnt/boot
mv /mnt/boot/resinOS_uEnv.txt.new /mnt/boot/resinOS_uEnv.txt
sync -f /mnt/boot
printf " done.\n"
