#!/bin/sh

set -o errexit

flash() {
    for line in $(cat $1); do
        part_name=$(cut -d ':' -f 1 <<< $line) 
        filename=$(cut -d ':' -f 2 <<< $line)
        
        dd oflag=dsync if="/opt/tegra-binaries/$filename" of="/dev/disk/by-partlabel/$part_name"
    done
}

flash "/opt/tegra-binaries/partition_specification.txt"
